- name: Stopping OpsRamp Shield Service
  shell: "{{ internal_cmd }} service opsramp-shield stop"
  args:
    warn: no
  no_log: True
  register: installationLog
  notify: Start shield service
- name: Stopping OpsRamp Agent Service
  shell: "{{ internal_cmd }} service opsramp-agent stop"
  args:
    warn: no
  no_log: True
  register: installationLog
  notify: Start agent service
